#!/usr/bin/perl -w
use strict;
our $nextclean=1;
our $rpmversion=0;
sub rbk(@)
{
    # FIXME: cleanup after disorderfs hack or when switching rpm versions between main and test repos
    $ENV{CLEAN}=(1 || $nextclean || ($rpmversion != $_[5]));
    $nextclean=$_[2];
    $rpmversion=$_[5];
    return system("rbkt", @_);
}
sub debugtry(@)
{
    my $result=<STDIN>;chomp($result);
    return $result;
}

sub run(@)
{
    print "trying @_\n";
    rbk(@_);
    #debugtry(@_);
}

sub stupid_bisect($$)
{
    my $min=shift;
    my $max=shift;
    if($#$max != $#$min) {die "need same size"}
    my @cur=@$max;
    for(my $i=$#cur; $i>=0; $i--) {
        next if($min->[$i] == $cur[$i]);
        $cur[$i]=$min->[$i];
        my $res=run(@cur);
        if($res == (1<<8)) {
            $cur[$i]=$max->[$i];
        }
    }
    print "cur: @cur\n";
    open(my $outfd, ">.rb.autoclassify") or die $!;
    print $outfd "@cur\n";
    return @cur;
}

# tweaks that may trigger build failures in some packages:
my @unstable=(0,0,1,1,1,1,1,0,0,1);
my @min=     (0,0,0,0,0,0,0,0,0);
my @max=@ARGV;
for(my $i=$#min; $i>=0; $i--) {
    $max[$i]=1 unless defined $max[$i];
}
stupid_bisect(\@min, \@max);

