#!/usr/bin/perl -w
# collect the correct versions of build dependencies
# input: a _buildenv file of an official build
# implicit input: hdrmd5cid.db - index of packages in IPFS
# output: symlinks to relevant rpms all in one dir

use strict;
use DB_File;
our $base = $ENV{PKGBASE}||"/ipfs";
our $dbname = $ENV{DBFILE}||"$ENV{HOME}/reproducibleopensuse/data/hdrmd5cid.db";
our %hdrdata;
tie(%hdrdata, "DB_File", $dbname, O_RDONLY) or die "error opening DB: $!";
my $infile = $ENV{IN} || "binaries/_buildenv";
system "rm -rf deps";
mkdir "deps";
open(my $infd, "<", $infile) or die "error opening $infile: $!";
while(<$infd>) {
    if(m/^  <bdep/) {
        next unless m/name="([^"]+)" hdrmd5="([^"]+)"/;
        my ($pkgname, $pkgid) = ($1, $2);
        my $pkg = $hdrdata{$pkgid};
        unless($pkg) {
		print "missing $_";
		next;
	}
        print "$pkg $pkgname\n";
        my $pkgbasename = $pkg ; $pkgbasename =~ s!.*/!!;
        symlink "$base/$pkg", "deps/$pkgname.rpm";
    }
}
