#!/bin/sh
#prereq: zypper -n in build-compare
: ${dir1:=binaries}
: ${dir2:=RPMS}

pushd $dir1
origrpms=$(ls *.rpm | grep -v "^::import::")
popd

pkgdiff=~/build-compare/pkg-diff.sh
test -e $pkgdiff || pkgdiff=/usr/lib/build/pkg-diff.sh
test -e $pkgdiff || exit 75

overall=0
overalldiffered=0
for f in $origrpms ; do
    # strip rebuild counter
    rpm=$(echo "$f" | sed 's/-[0-9.]*\(\.[a-z0-9_]*\.rpm\)$/-*\1/')
    f1=$dir1/$f
    f2=$dir2/$rpm
    #ls -l $f1 $f2
    cmp $f1 $f2
    compareresult=$?
    [[ $compareresult = 0 ]] || overalldiffered=$((overalldiffered+1))
    [[ $compareresult = 0 ]] || $pkgdiff -a $f1 $f2
    compareresult=$?
    [[ $compareresult = 0 ]] || overall=1
done

echo $overalldiffered > .build-differed
echo "overalldiffered=$overalldiffered (not bit-by-bit identical)"
echo overall=$overall
echo $overall > .build-compare-retval
exit $overalldiffered
