#!/bin/sh
scriptdir=$(dirname $0)
for p in "$@" ; do
    popd > /dev/null
    if ! pushd $p > /dev/null ; then
        echo "Error: could not find $p"
        continue
    fi
    $scriptdir/compareone
done

