#!/bin/bash
scriptdir=$(dirname $BASH_SOURCE)
p=$(basename $(pwd))
: ${dir1:=binaries}
: ${dir2:=RPMS}
    if ! test -e $dir1 || test -z "$(find $dir2/ -maxdepth 1 -name '*.rpm' -print -quit)" ; then
         echo "result:$p=notbuilt"
         exit 0
    fi
    o=$dir2/$p-compare.out
    $scriptdir/compare | tee $o
    ret=${PIPESTATUS[0]}
    [ $ret = 0 ] && rm -f $o
    jsonresultcache .
    echo "result:$p=$ret"
