#!/bin/bash
if [[ $1 ]] ; then
    cd "$1" || exit 4
fi
cd .osc || { echo "^^ $1 ^^" ; exit 5 ; }

maxt=0
for f in * ; do
    case "$f" in
        _files|_meta|_build_repositories|_last_buildroot|_buildconfig-*|_buildinfo-*)
		true
		;;
	*)
		t=$(stat -c %Y "$f")
		[[ $t -gt $maxt ]] && maxt=$t
		;;
    esac
done
touch -d@$maxt _files _meta

