#!/bin/sh

processone()
{
  [ -e "$d/.osc-build-retval" ] || return 5 # not yet tried to build
  if [ -e "$d/.build-jsonresult" ] ; then
    find "$d" -maxdepth 1 -newer "$d/.build-jsonresult" | grep -q . || return 0 # already done
  fi
  jsonresult "$d" > "$d/.build-jsonresult"
}

while true; do
  d=${1:-.}
  shift
  processone
  [ -n "$1" ] || exit 0 # done
done
