#!/usr/bin/perl -w
use strict;
use JSON;
my @result = ();
undef $/;
for my $dir (@ARGV) {
    my $f = "$dir/.build-jsonresult";
    open(my $fd, "<", $f) or next;
    my $jsonin = <$fd>;
    next unless $jsonin; # skip empty files
    my $oneresult = eval {decode_json($jsonin)};
    if($@) { die "$@ in $dir" }
    push(@result, @$oneresult);
}
print JSON->new->ascii->pretty->allow_nonref->canonical->encode(\@result);
