#!/bin/bash
export CLEAN=1
pkg=$(basename $(pwd))
if [[ -e _multibuild ]] ; then
    [[ $multibuilds ]] ||
        multibuilds=$(fgrep -v i686 _multibuild | grep -v '<!--' | fgrep -e package -e flavor | sed 's/.*>\([^<>]*\)<.*/\1/')
else
    multibuilds=
fi
    for multibuild in "" $multibuilds ; do
        [[ $multibuild =~ test ]] && continue
	if [[ -n $multibuild ]] ; then
            export oscbuildparams="-M=$multibuild"
            if [[ -e $multibuild.spec ]] ; then
	        export spec=$multibuild.spec
            fi
	    osc api "/build/openSUSE:Factory/_result?package=$pkg:$multibuild&repository=standard&arch=x86_64" | grep -E 'code="(excluded|disabled|unresolvable)"' && continue
	else
	    osc api "/build/openSUSE:Factory/_result?package=$pkg&repository=standard&arch=x86_64" | grep -E 'code="(excluded|disabled|unresolvable)"' && continue
	fi
	echo "running $pkg $oscbuildparams"
	mkdir -p RPMS ; echo $multibuild > RPMS/_multibuild
        if ! rbkt "$@" ; then
		if [ -n "$multibuild" ] || ! grep -q status.....notforus .build-jsonresult ; then
			exit 27
		fi
	fi
	echo "success $(basename $(pwd)) $oscbuildparams"
    done
touch .rb.multibuildrbkall.succeeded
