#!/bin/bash
if [[ -e _multibuild ]] ; then
    [[ $multibuild ]] ||
        multibuild=$(grep -F -v i686 _multibuild | grep -v '<!--' | grep -F -m 1 -e package -e flavor | sed 's/.*>\([^<>]*\)<.*/\1/')
    if [[ $multibuild ]] && ! [[ $multibuild =~ test ]] ; then
        export oscbuildparams+=" -M=$multibuild"
        if [[ -e $multibuild.spec ]] ; then
	    export spec=$multibuild.spec
        fi
    fi
fi
exec rbk "$@" || exit 27
