#!/bin/bash
export CLEAN=1
if [[ -e _multibuild ]] ; then
    [[ $multibuilds ]] ||
        multibuilds=$(fgrep -v i686 _multibuild | grep -v '<!--' | fgrep -e package -e flavor | sed 's/.*>\([^<>]*\)<.*/\1/')
else
    multibuilds=
fi
    for multibuild in "" $multibuilds ; do
        [[ $multibuild =~ test ]] && continue
	if [[ -n $multibuild ]] ; then
            export oscbuildparams="-M=$multibuild"
	fi
	echo "running $(basename $(pwd)) $oscbuildparams"
	mkdir -p RPMS ; echo $multibuild > RPMS/_multibuild
        if ! rbkt "$@" ; then
		if [ -n "$multibuild" ] || ! grep -q status.....notforus .build-jsonresult ; then
			exit 27
		fi
	fi
	echo "success $(basename $(pwd)) $oscbuildparams"
    done
touch .rb.multibuildrbkall.succeeded
