#!/bin/bash
if [[ -e _multibuild ]] ; then
    [[ $multibuild ]] ||
         multibuild=$(fgrep -v i686 _multibuild | fgrep -m 1 package | sed 's/.*>\([^<>]*\)<.*/\1/')
    if ! [[ $multibuild =~ test ]] ; then
        export oscbuildparams="-M $multibuild"
    fi
fi
exec rbk "$@" || exit 27
