#!/bin/bash
: ${slot:=${1:=4}}
if [ "$2" = 1 ] ; then rbdebug=1 ; fi
[ $(id -u) = 0 ] || exec sudo $BASH_SOURCE $slot
for x in "" b ; do
    b=/var/tmp/build-root.$slot$x
    mkdir -p $b/.mount/
    mount -o loop $b/img $b/.mount/ || mount --bind $b/ $b/.mount/
    for m in proc sys dev ; do mount --bind /$m $b/.mount/$m ; done
done
echo mounted $b/.mount
[ -n "$rbdebug" ] && bash -i
diff -ruN /var/tmp/build-root.${slot}{,b}/.mount/home/abuild/rpmbuild/ > .rb.buildroot.diff

for x in "" b ; do
    b=/var/tmp/build-root.$slot$x
    for m in proc sys dev ; do umount $b/.mount/$m ; done
    umount $b/.mount/
done
