#!/bin/sh
: ${slot:=4}
for x in "" b ; do
    b=/var/tmp/build-root.$slot$x
    mount -o loop $b/img $b/.mount/
    for m in proc sys dev ; do mount --bind /$m $b/.mount/$m ; done
done
echo mounted $b/.mount
[[ $rbdebug ]] && bash -i
diff -ruN /var/tmp/build-root.${slot}{,b}/.mount/home/abuild/rpmbuild/ > .rb.buildroot.diff

for x in "" b ; do
    b=/var/tmp/build-root.$slot$x
    for m in proc sys dev ; do umount $b/.mount/$m ; done
    umount $b/.mount/
done
