#!/bin/bash -e
# rebuild with KVM mode
pkg=$(basename `pwd`)
years=15
if grep -q "^$pkg$" ~/reproducibleopensuse/exceptions.neardate ; then
    years=1
fi
: ${slot:=4}
: ${clean:=--clean --offline}
: ${project:=home:bmwiedemann:reproducible}
: ${repo:=openSUSE_Tumbleweed}
: ${datediff:=$(((((365*$years+36)*24+13)*60+17)*60))}
: ${host1:=sles12a}
: ${host2:=sles12b}
: ${parallelism:=4}
: ${parallelism2:=2}
now=$(date +%s)
later=$(date --date=@$((now+datediff)) -u "+%FT%T")
export vmtype="--vm-type=kvm"
export OSC_BUILD_ROOT=/var/tmp/build-root.${slot}/
export VM_CUSTOMOPT=""
osc up -S
mkdir -p RPMS
osc build ${oscbuildextrapkg} --preload --nopreinstallimage --noservice --vm-type=kvm --alternative-project=$project ${oscbuildparams} $repo $pkg.spec 2>&1 | tee RPMS/.build.log2
if (( ${PIPESTATUS[0]} )) ; then
    if grep -q "Error: build description file named '.*does not exist" RPMS/.build.log2 ; then
        echo 2
    else
        echo 33
    fi > .osc-build-retval
    exit 33
fi
rm -f .build-differed .build-rbkt
clean+=" --release=0.0"
export clean
clean="$clean -j${parallelism}" HOST=$host1 OUTDIR=RPMS.2017 rebuild &
pid=$!
export VM_CUSTOMOPT="-rtc base=$later"
export OSC_BUILD_ROOT=/var/tmp/build-root.${slot}b/
clean="$clean -j${parallelism2}" HOST=$host2 OUTDIR=RPMS rebuild
wait $pid
dir1=RPMS.2017 compareone
grep '^0$' .build-differed || oscmount
