#!/usr/bin/perl -w
# build one package with reduced indeterminism
# returns 0 for a reproducible build
# returns 1 for an unreproducible build
# returns 255 for a failed build
# usage:
#  CLEAN=1 rbkt 0 0 1 0 0 0 # to build with sorted filesystem
#  CLEAN=1 rbkt 1 1 1 1 1 1 1 1 1 1 # to build with as little indeterminism as possible


use strict;
sub rbk(@)
{
    my @tweakbits=@_;
    my @extrapkg=();
    if($ENV{CLEAN}) { $ENV{clean}="--clean --offline"} else { $ENV{clean}="--offline" }
    # bit 1
    if(shift) { $ENV{datediff}=100 }
    # bit 2
    my $hosttweak=shift||0;
    if($hosttweak&1) { $ENV{host2}="sles12a" }
    if($hosttweak&2) { push(@extrapkg, "reproducible-faketools-hostname") }
    # bit 3
    if(shift) { push(@extrapkg, "reproducible-faketools-filesys") }
    if(shift) { push(@extrapkg, "reproducible-faketools-date") }
    if(shift) { $ENV{rbsnd}=1 } # use strip-nondeterminism
    # bit 6
    if(shift) { $ENV{project}="home:bmwiedemann:reproducible:test" }
    if(shift) { push(@extrapkg, "reproducible-faketools-tar") }
    # bit 8
    if(shift) { $ENV{parallelism}=1; $ENV{parallelism2}=1 }
    if(shift) { push(@extrapkg, "reproducible-faketools-aslr") }
    # bit 10
    if(shift) { push(@extrapkg, "reproducible-faketools-pid") }
    if(shift) { push(@extrapkg, "reproducible-faketools-random") }
    if(shift) { $ENV{cputype2}="host" }
    if(shift) { push(@extrapkg, "reproducible-faketools-faketime") }
    if(shift) { push(@extrapkg, "reproducible-faketools-strace") } # get extra r-b debug info
    if(@extrapkg) { $ENV{oscbuildextrapkg}=join " ", map {"--extra-pkgs=$_"} @extrapkg }
    system("rbk");
    system("echo @tweakbits > .build-rbkt");
    system("jsonresultcache ."); # update with tweakbits
    my $resultfile=$ENV{rbminor}?".build-compare-retval":".build-differed";
    open(my $resultfd, "<", $resultfile) || die $!;
    my $result=<$resultfd>;chomp($result);
    if($result>1) {$result=1}
    return $result;
}

sub run(@)
{
    #print "trying @_\n";
    rbk(@_);
}

exit run(@ARGV);
