#!/bin/bash
# sanity check
bad=
for p in * ; do test -e $p/.osc/_files || { echo $p ; bad=1 ; } ; done
[[ $bad ]] && exit 32

exec 3>&1
exec > ~/tmp/rbstats.txt

echo -n "total-packages: "
ls | wc -l
buildtried=$(ls */.build-jsonresult | wc -l)
grep -l '"status" : "FTBFS"' */.build-jsonresult | cut -d/ -f1 > ~/tmp/failed-builds.txt
grep -l '"status" : "unreproducible"' */.build-jsonresult | cut -d/ -f1 > ~/tmp/differed-builds.txt
grep -l 'build_compare_status" : "reproducible"' */.build-jsonresult | cut -d/ -f1 > ~/tmp/minor-differed-builds.txt
grep -v '^0$' */.build-compare-retval | cut -d/ -f1 > ~/tmp/build-compare-differed-builds.txt
grep -v '^0$' */.build-differed-nachbau | cut -d/ -f1 > ~/tmp/differed-builds-nachbau.txt
grep -v '^0$' */.build-compare-retval-nachbau | cut -d/ -f1 > ~/tmp/build-compare-differed-builds-nachbau.txt
grep -l '"verified" : 0' */.build-jsonresult | cut -d/ -f1 > ~/tmp/build-verify-failed.txt
buildunverified=$(wc -l < ~/tmp/build-verify-failed.txt)
buildsemiverified=$(grep '"verified" : [12]' */.build-jsonresult | wc -l)
buildverified=$(grep '"verified" : 2' */.build-jsonresult | wc -l)
buildfailed=$(wc -l < ~/tmp/failed-builds.txt)
buildfailedarch=$(grep "\"status\" : \"notforus\"" */.build-jsonresult | wc -l)
buildfailedwaitdep=$(grep "\"status\" : \"waitdep\"" */.build-jsonresult | wc -l)
#buildna=$(grep '^[2]$' */.osc-build-retval | wc -l)
buildsucceeded=$(grep '^0$' */.osc-build-retval | wc -l)
echo "build-tried: $buildtried"
echo "build-failed: $((buildfailed))"
echo "build-n-a: $((buildfailedarch+buildfailedwaitdep))"
echo "build-succeeded: $buildsucceeded"
[[ $((buildfailed+buildfailedarch+buildfailedwaitdep+buildsucceeded)) == $buildtried ]] || { echo sanity check failed ; exit 27; }
#osc prjresults --csv --arch=x86_64 --repo=standard openSUSE:Factory > ~/tmp/oscpr
grep -e ';failed$' -e ';unresolvable$' -e ';disabled$' ~/tmp/oscpr > ~/tmp/oscpr.failed
echo -n "build-official-failed+na: "
wc -l < ~/tmp/oscpr.failed
comparefailed=$(grep -v '^0$' */.build-compare-retval | wc -l)
bitidentical=$(grep '^0$' */.build-differed | wc -l)
echo "build-compare-failed: $comparefailed"
echo "build-compare-succeeded: "$(($buildsucceeded-$comparefailed))
echo "verify-failed: $buildunverified"
echo "verified-semi-reproducible: $buildsemiverified"
echo "verified-bit-identical: $buildverified"
echo "bit-by-bit-identical: $bitidentical" # needs rpm patches
echo "not-bit-by-bit-identical: $(wc -l < ~/tmp/differed-builds.txt)"
echo "not-bit-by-bit-identicalcheck: $((buildsucceeded-bitidentical))"


for p in $(cat ~/tmp/failed-builds.txt) ; do test -d $p && ! cut -d\; -f1 ~/tmp/oscpr.failed | grep -q "^$p$" && ! grep -q -e '"status" : "notforus"' -e '"status" : "waitdep"' $p/.build-jsonresult && echo $p ; done > ~/tmp/failchecklist 2>/dev/null

exec 1>&3
cat ~/tmp/rbstats.txt
if [[ $final = 1 ]] ; then
    cat */RPMS*/checksums > ~/tmp/checksums.txt
    for p in * ; do jsonresultcache "$p" ; done
    jsonresultmerge * > ~/tmp/reproducible.json
    showrings > ~/tmp/unreproduciblerings.txt
    grep . */RPMS/build-time | sort -n -t: -k2 | perl -pe 's{/.*:}{:}' > ~/tmp/build-time.txt
fi
echo "untracked dirs:"
for p in * ; do test -d $p && test -e $p/.osc-build-retval || echo -n "$p " ; done
