#!/bin/sh

: ${OSC_BUILD_ROOT:="/var/tmp/build-root/standard-x86_64"}
: ${clean:=--clean}
export OSC_BUILD_ROOT

#vmtype="--vm-type=kvm"
rm -rf binaries $OSC_BUILD_ROOT/home/abuild/rpmbuild/RPMS/ $OSC_BUILD_ROOT/.mount/.build.packages/RPMS/
osc build --noservice $vmtype $clean $(basename `pwd`).spec "$@"
echo $? > .osc-build-retval
if [ `cat .osc-build-retval` -gt 0 ] ; then
    cp -a $OSC_BUILD_ROOT/.build.log .
fi
rm -rf RPMS
mkdir -p RPMS
cp -a $OSC_BUILD_ROOT/home/abuild/rpmbuild/RPMS/*/*.rpm $OSC_BUILD_ROOT/.mount/.build.packages/RPMS/*/*.rpm RPMS/
test -n "$(find RPMS/ -maxdepth 1 -name '*.rpm' -print -quit)" &&\
  ! test -e binaries &&\
  true #osc getbinaries standard x86_64
