#!/bin/bash
: ${d:=$(date -u +%Y%m%d)}
lastmonth=$(date -d@$(($(date +%s)-30*24*60*60)) +%Y-%m)
cat - <<EOF
Hi,

last month's status:
https://lists.opensuse.org/opensuse-factory/$lastmonth/msg0FIXME.html

Last months' reproducible builds project updates (including my work):
https://reproducible-builds.org/reports/$lastmonth/

I uploaded https://rb.zq1.de/compare.factory-$d/ today
and rbstats are:
EOF

ring0=$(wc -l < /tmp/ring0)
ring1=$(wc -l < /tmp/ring1)
ringtotal=$((ring0+ring1))
ring0=$(($(fgrep -nm 1 -- "--- ring1 ---" ~/tmp/unreproduciblerings.txt | cut -d: -f1)-2))
ring1=$(($(fgrep -nm 1 -- "--- ringsle15 " ~/tmp/unreproduciblerings.txt | cut -d: -f1)-3-ring0))

compiled=$(echo $(grep build-succeeded ~/tmp/rbstats.txt| cut -d: -f2))
buildcomparefailed=$(echo $(grep build-compare-failed ~/tmp/rbstats.txt| cut -d: -f2))
unreproducible=$(echo $(grep not-bit-by-bit-identical: ~/tmp/rbstats.txt| cut -d: -f2))


cat << EOF
$(./rbstatsdiff < ~/f/.rbstats.ref)

https://rb.zq1.de/compare.factory-$d/graph.png
shows the change over time

https://rb.zq1.de/compare.factory-$d/unreproduciblerings.txt
lists very unreproducible core packages (bootstrap+DVD)

Of the badly unreproducible packages,
$ring0 were in ring0
$ring1 were in ring1

That makes it $((ring0+ring1))/$ringtotal => $(perl -e '@a=@ARGV;printf("%.2f %", 100*($a[0]+$a[1])/$a[2])' $ring0 $ring1 $ringtotal)
which is below the overall average of
$buildcomparefailed/$compiled => $(perl -e '@a=@ARGV;printf("%.2f %", 100*$a[0]/$a[1])' $buildcomparefailed $compiled)

$unreproducible/$compiled => $(perl -e '@a=@ARGV;printf("%.2f %", 100*$a[0]/$a[1])' $unreproducible $compiled) of packages are not perfectly reproducible
EOF
