#!/bin/sh
unset CDPATH
p1="unresolvable: nothing provides librpm.so.3"
p2="Kernel panic"
p3="error: unpacking of archive failed on file"
p4="No buildstatus set, either the base system is broken"
p5="create archive failed on file"
p6="unsupported package type. magic"
p7="Starting Emergency Shell"
pssl="SSL Error: unexpected eof"
emem="Out of memory: Kill process"
emem2="out of memory allocating"
eswi="Failed to start Switch Root"
estruc=" failed: Structure needs cleaning"
epatch=" hunk FAILED -- saving rejects to file"
p400="Server returned an error: HTTP Error 400: Bad Request"
p500="Server returned an error: HTTP Error 500: Internal Server Error"
p502="Server returned an error: HTTP Error 502: Bad Gateway"
p503="Server returned an error: HTTP Error 503: Service Temporarily Unavailable"
w1="W: python-bytecode-inconsistent-mtime"
fgrep "[Errno 2] No such file or directory: '/var/tmp/osbuild-packagecache/home:bmwiedemann:reproducible/_pubkey" */RPMS*/.build.log2
fgrep -e "$p1" -e "$p2" -e "$p3" -e "$p4" -e "$p5" -e "$p6" -e "$p7" -e "$pssl" -e "$eswi" -e "$estruc" -e "$epatch" -e "$p400" -e "$p500" -e "$p502" -e "$p503" -e "$emem" -e "$emem2" */RPMS*/.build.log2
grep "in-progress" */RPMS*/.osc-build-retval
#post-process with
#grep python-bytecode-inconsistent-mtime | grep -o "/usr/lib[^ ]*" /root/tmp/bytecode-inconsistent.txt|sort -u > /root/tmp/bytecode-inconsistent2.txt

# compare results for failed build
if true ; then
for p in * ; do (
    cd $p &&\
    test -e .osc-build-retval &&\
    grep -q -v '^0$' .osc-build-retval &&\
    ( test -e .build-compare-retval || test -e .build-differed ) &&\
    rm -f .build-compare-retval .build-differed
  )
done
fi

# notify about successful build without compare results - might have half-failed
for p in * ; do (
    ! echo $p | grep -q -e '-testsuite$' -e perl-PAR-Packer-test -e rpmlint-tests &&\
    cd $p &&\
    test -e .osc-build-retval &&\
    grep -q '^0$' .osc-build-retval &&\
    ( ! test -e .build-compare-retval || ! test -e .build-differed ) &&\
    echo $p
  )
done
