#!/bin/sh
: ${slot:=4}
[[ -n "$project" ]] && params="--alternative-project=$project"
export OSC_BUILD_ROOT=/var/tmp/build-root.${slot}/
nice -n 17 osc build --clean --nocheck --noservice --trust-all-projects -x reproducible-faketools-strace $params "$@"
cp -a $OSC_BUILD_ROOT/.build.log .rb.build.log.strace
