#!/bin/sh
: ${slot:=4}
export OSC_BUILD_ROOT=/var/tmp/build-root.${slot}/
osc build --clean --noservice --trust-all-projects --alternative-project home:bmwiedemann:reproducible -x reproducible-faketools-strace "$@"
cp -a $OSC_BUILD_ROOT/.build.log .rb.build.log.strace
