#!/bin/sh
sed -e "s/0x[0-9a-f][0-9a-f]*/xxxxy/g" \
    -e "s/^[0-9][0-9]*//" \
    -e "s/si_pid=[0-9][0-9]*/si_pid=NNNN/" \
    -e 's/\(vfork.* = \)[0-9][0-9]*$/\1NNNN/' \
    -e 's/\(wait4.* = \)[0-9][0-9]*$/\1NNNN/' \
    -e 's/\(clone.* = \)[0-9][0-9]*$/\1NNNN/' \
    -e 's/\(getpid.* = \)[0-9][0-9]*$/\1NNNN/' \
    -e 's/\(getppid.* = \)[0-9][0-9]*$/\1NNNN/' \
    -e 's/\(getpgrp.* = \)[0-9][0-9]*$/\1NNNN/' \
    -e 's/\(rt_sigreturn.* = \)[0-9][0-9]*$/\1NNNN/' \
    -e 's/\(wait4(\)[0-9][0-9]*/\1NNNN/' \
    "$@"
